## 1

In [26]:
import pandas as pd
import numpy as np
import requests

In [27]:
pd.options.display.float_format = '{:.2f}'.format
auto_df=pd.read_json('../ex02/auto.json')
print(auto_df.info())
auto_df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 725 entries, 0 to 724
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CarNumber  725 non-null    object
 1   Refund     725 non-null    int64
 2   Fines      725 non-null    float64
 3   Make       725 non-null    object
 4   Model      716 non-null    object
dtypes: float64(1), int64(1), object(3)
memory usage: 28.4+ KB
None

        CarNumber  Refund    Fines    Make    Model
0    Y163O8161RUS       2  3200.00    Ford    Focus
1     E432XX77RUS       1  6500.00  Toyota    Camry
2     7184TT36RUS       1  2100.00    Ford    Focus
3    X582HE161RUS       2  2000.00    Ford    Focus
4    92918M178RUS       1  5700.00    Ford    Focus
..            ...     ...      ...     ...      ...
720  Y163O8161RUS       2  1600.00    Ford    Focus
721  M0309X197RUS       1 22300.00    Ford    Focus
722  O673E8197RUS       2   600.00    Ford    Focus
723  8610T8154RUS       1  2000.00    Ford    Focus
724  H419XE197RUS       2  8594.59  Toyota  Corolla

[725 rows x 5 columns]

## 2

In [28]:
samples=auto_df.sample(n=200, random_state=21, replace=True)
samples

        CarNumber  Refund    Fines        Make   Model
207  Y351O8197RUS       1  1500.00        Ford   Focus
48    H917TC36RUS       2  4000.00        Ford   Focus
368  C589EY154RUS       1  4500.00        Ford   Focus
120   K846YE77RUS       2  2000.00  Volkswagen  Passat
419  X4108H125RUS       2  1300.00        Ford   Focus
..            ...     ...      ...         ...     ...
587  M942OT152RUS       1  2000.00        Ford   Focus
595  Y187O8161RUS       2   400.00        Ford   Focus
365  7064C8197RUS       1 12800.00  Volkswagen  Passat
474  8437XX154RUS       2   800.00        Ford   Focus
592   C410X938RUS       2  2200.00        Ford   Focus

[200 rows x 5 columns]

In [29]:
samples['Fines']=auto_df['Fines'].sample(n=200, random_state=21, replace=True).values
samples['Refund']=auto_df['Refund'].sample(n=200, random_state=21, replace=True).values

print('Original shape: ', auto_df.shape)
auto_df= pd.concat([auto_df, samples], ignore_index=True)
print('Enriched shape : ', auto_df.shape)

Original shape:  (725, 5)
Enriched shape :  (925, 5)

In [30]:
auto_df.count()

CarNumber    925
Refund       925
Fines        925
Make         925
Model        914
dtype: int64

## 3

In [31]:
np.random.seed(21)
size=auto_df.shape[0]
year=pd.Series(np.random.randint(1980, 2020,size=size))
year

0      1989
1      1995
2      1984
3      2015
4      2014
       ...
920    1981
921    1992
922    2007
923    2005
924    1997
Length: 925, dtype: int64

In [32]:
year.name='Year'
fines=pd.concat([auto_df, year], axis=1)
fines.head()

      CarNumber  Refund   Fines    Make  Model  Year
0  Y163O8161RUS       2 3200.00    Ford  Focus  1989
1   E432XX77RUS       1 6500.00  Toyota  Camry  1995
2   7184TT36RUS       1 2100.00    Ford  Focus  1984
3  X582HE161RUS       2 2000.00    Ford  Focus  2015
4  92918M178RUS       1 5700.00    Ford  Focus  2014

## 4

In [33]:
surnames=pd.read_json('../../datasets/surname.json', orient='records')

surnames.columns = surnames.iloc[0]
surnames=surnames[1:].reset_index(drop=True)
surnames

0       NAME    COUNT RANK
0      ADAMS   427865   42
1      ALLEN   482607   33
2    ALVAREZ   233983   92
3   ANDERSON   784404   15
4     BAILEY   277845   72
..       ...      ...  ...
95  WILLIAMS  1625252    3
96    WILSON   801882   14
97      WOOD   250715   84
98    WRIGHT   458980   35
99     YOUNG   484447   32

[100 rows x 3 columns]

In [34]:
surnames.shape

(100, 3)

In [35]:
np.random.seed(21)

# This approach is pretty complicted
surnames_series=pd.Series(surnames['NAME'].iloc[np.random.randint(0, surnames.shape[0], size=size)])

# previous but good approach
# surname_series = surname['NAME'].sample(n=size, replace=True, random_state=21).reset_index(drop=True)
surnames_series

73    RICHARDSON
79          ROSS
56        MORGAN
4         BAILEY
48         LOPEZ
         ...
73    RICHARDSON
1          ALLEN
89        TORRES
51       MENDOZA
33     HERNANDEZ
Name: NAME, Length: 925, dtype: object

In [36]:
owners=pd.DataFrame()
surnames_series=surnames_series.reset_index(drop=True)
owners['CarNumber']=auto_df['CarNumber']
owners['SURNAME']=surnames_series
owners

        CarNumber     SURNAME
0    Y163O8161RUS  RICHARDSON
1     E432XX77RUS        ROSS
2     7184TT36RUS      MORGAN
3    X582HE161RUS      BAILEY
4    92918M178RUS       LOPEZ
..            ...         ...
920  M942OT152RUS  RICHARDSON
921  Y187O8161RUS       ALLEN
922  7064C8197RUS      TORRES
923  8437XX154RUS     MENDOZA
924   C410X938RUS   HERNANDEZ

[925 rows x 2 columns]

In [37]:
fines

        CarNumber  Refund    Fines        Make   Model  Year
0    Y163O8161RUS       2  3200.00        Ford   Focus  1989
1     E432XX77RUS       1  6500.00      Toyota   Camry  1995
2     7184TT36RUS       1  2100.00        Ford   Focus  1984
3    X582HE161RUS       2  2000.00        Ford   Focus  2015
4    92918M178RUS       1  5700.00        Ford   Focus  2014
..            ...     ...      ...         ...     ...   ...
920  M942OT152RUS       1  2000.00        Ford   Focus  1981
921  Y187O8161RUS       2   400.00        Ford   Focus  1992
922  7064C8197RUS       1 12800.00  Volkswagen  Passat  2007
923  8437XX154RUS       2   800.00        Ford   Focus  2005
924   C410X938RUS       2  2200.00        Ford   Focus  1997

[925 rows x 6 columns]

In [38]:
new_columns=pd.DataFrame({
    'CarNumber': ['A123BC161RUS', 'X777XX197RUS', 'M555MM163RUS', 'K900KK199RUS', 'H432HH154RUS'],
    'Make': ['Ford', 'Skoda', 'Toyota', 'Volkswagen', 'Ford'],
    'Model': ['Focus', 'Octavia', 'Camry', 'Passat', 'Fiesta'],
    'Fines': [3200, 15000, 6000, 8500, 2000],
    'Refund': [0, 1, 2, 0, 1],
    'Year': [2012, 2018, 2016, 2014, 2010]
})

print('Original shape: ', fines.shape)
fines= pd.concat([fines, new_columns], ignore_index=True)
print('Shape with new features : ', fines.shape)

Original shape:  (925, 6)
Shape with new features :  (930, 6)

In [39]:
owners.drop_duplicates(subset='SURNAME', inplace=True)
owners

        CarNumber     SURNAME
0    Y163O8161RUS  RICHARDSON
1     E432XX77RUS        ROSS
2     7184TT36RUS      MORGAN
3    X582HE161RUS      BAILEY
4    92918M178RUS       LOPEZ
..            ...         ...
238  7831C8197RUS       ORTIZ
267   T6439O50RUS     JOHNSON
270  O752MX161RUS     JACKSON
299  8611T8154RUS    WILLIAMS
525  O64097197RUS      MILLER

[100 rows x 2 columns]

In [40]:
owners=owners.iloc[:-20].copy()
owners

        CarNumber     SURNAME
0    Y163O8161RUS  RICHARDSON
1     E432XX77RUS        ROSS
2     7184TT36RUS      MORGAN
3    X582HE161RUS      BAILEY
4    92918M178RUS       LOPEZ
..            ...         ...
132  E42577152RUS       PRICE
149  O77997197RUS      BROOKS
151  M741T9152RUS    THOMPSON
157  E316EH197RUS      FLORES
171  T686EO197RUS     COLLINS

[80 rows x 2 columns]

In [41]:
three_new_cols = pd.DataFrame({
    'CarNumber':['Y163O8161RUS', 'E432XX77RUS', '92918M178RUS'],
    'SURNAME':['RICHARDSON', 'ROSS', 'LOPEZ']
})

print('Original shape: ', owners.shape)
owners=pd.concat([owners, three_new_cols],ignore_index=True)
print('Changed shape: ', owners.shape)

Original shape:  (80, 2)
Changed shape:  (83, 2)

In [42]:
df_inner = fines.merge(owners, on='CarNumber', how='inner')

df_outer=fines.merge(owners, on='CarNumber', how='outer')

df_left=fines.merge(owners, on='CarNumber', how='left')

df_right=fines.merge(owners, on='CarNumber', how='right')

In [43]:
df_inner

        CarNumber  Refund   Fines    Make  Model  Year     SURNAME
0    Y163O8161RUS       2 3200.00    Ford  Focus  1989  RICHARDSON
1    Y163O8161RUS       2 3200.00    Ford  Focus  1989  RICHARDSON
2     E432XX77RUS       1 6500.00  Toyota  Camry  1995        ROSS
3     E432XX77RUS       1 6500.00  Toyota  Camry  1995        ROSS
4     7184TT36RUS       1 2100.00    Ford  Focus  1984      MORGAN
..            ...     ...     ...     ...    ...   ...         ...
174  Y163O8161RUS       2 3200.00    Ford  Focus  2017  RICHARDSON
175  8603T8154RUS       1 3000.00    Ford  Focus  2011    MITCHELL
176  Y163O8161RUS       2 1600.00    Ford  Focus  2017  RICHARDSON
177  Y163O8161RUS       2 1600.00    Ford  Focus  2017  RICHARDSON
178  H963HY161RUS       1 1400.00    Ford  Focus  2013    CAMPBELL

[179 rows x 7 columns]

In [44]:
df_outer

        CarNumber  Refund    Fines  Make  Model  Year SURNAME
0    704687163RUS       2  1400.00  Ford  Focus  2004     NaN
1    704787163RUS       2  2800.00  Ford  Focus  1992     NaN
2    704987163RUS       2  8594.59  Ford  Focus  1985     NaN
3    705287163RUS       2  2000.00  Ford  Focus  1980     NaN
4    705387163RUS       2   700.00  Ford  Focus  1987     NaN
..            ...     ...      ...   ...    ...   ...     ...
948  Y969O8197RUS       2  7800.00  Ford  Focus  1992     NaN
949  Y973O8197RUS       2  8594.59  Ford  Focus  2005   YOUNG
950  Y973O8197RUS       1 34800.00  Ford  Focus  2003   YOUNG
951  Y973O8197RUS       1 69600.00  Ford  Focus  2017   YOUNG
952  Y973O8197RUS       1 69600.00  Ford  Focus  2000   YOUNG

[953 rows x 7 columns]

In [45]:
df_left

        CarNumber  Refund    Fines        Make    Model  Year     SURNAME
0    Y163O8161RUS       2  3200.00        Ford    Focus  1989  RICHARDSON
1    Y163O8161RUS       2  3200.00        Ford    Focus  1989  RICHARDSON
2     E432XX77RUS       1  6500.00      Toyota    Camry  1995        ROSS
3     E432XX77RUS       1  6500.00      Toyota    Camry  1995        ROSS
4     7184TT36RUS       1  2100.00        Ford    Focus  1984      MORGAN
..            ...     ...      ...         ...      ...   ...         ...
948  A123BC161RUS       0  3200.00        Ford    Focus  2012         NaN
949  X777XX197RUS       1 15000.00       Skoda  Octavia  2018         NaN
950  M555MM163RUS       2  6000.00      Toyota    Camry  2016         NaN
951  K900KK199RUS       0  8500.00  Volkswagen   Passat  2014         NaN
952  H432HH154RUS       1  2000.00        Ford   Fiesta  2010         NaN

[953 rows x 7 columns]

In [46]:
df_right

        CarNumber  Refund   Fines    Make  Model  Year     SURNAME
0    Y163O8161RUS       2 3200.00    Ford  Focus  1989  RICHARDSON
1    Y163O8161RUS       2 1600.00    Ford  Focus  1980  RICHARDSON
2    Y163O8161RUS       2 3200.00    Ford  Focus  2019  RICHARDSON
3    Y163O8161RUS       2 3200.00    Ford  Focus  2017  RICHARDSON
4    Y163O8161RUS       2 1600.00    Ford  Focus  2017  RICHARDSON
..            ...     ...     ...     ...    ...   ...         ...
174   E432XX77RUS       1 6500.00  Toyota  Camry  1995        ROSS
175  92918M178RUS       1 5700.00    Ford  Focus  2014       LOPEZ
176  92918M178RUS       2 7600.00    Ford  Focus  2009       LOPEZ
177  92918M178RUS       1 1900.00    Ford  Focus  2001       LOPEZ
178  92918M178RUS       1 1900.00    Ford  Focus  1982       LOPEZ

[179 rows x 7 columns]

## 5

In [47]:
pivot = fines.pivot_table(
    index=['Make', 'Model'],   # Multi‑index rows
    columns='Year',            # Years across columns
    values='Fines',            # Sum of fines
    aggfunc='sum',
    fill_value=np.nan          # keep NaN so table looks like example
)

pivot

Year                   1980      1981      1982     1983      1984      1985  \
Make       Model
Ford       Fiesta       NaN       NaN       NaN      NaN       NaN       NaN
           Focus   62394.59 395589.17 140383.76 63100.00 111294.59 189583.76
           Mondeo       NaN       NaN       NaN      NaN       NaN       NaN
Skoda      Octavia 12494.59       NaN   6900.00 11594.59   1200.00  10294.59
Toyota     Camry   18500.00   8594.59       NaN  7200.00       NaN       NaN
           Corolla      NaN       NaN   2000.00      NaN       NaN       NaN
Volkswagen Golf    30900.00       NaN       NaN  8594.59    300.00  24000.00
           Jetta        NaN       NaN       NaN      NaN       NaN       NaN
           Passat       NaN   4600.00       NaN  3200.00  10000.00   5000.00
           Touareg      NaN       NaN       NaN      NaN       NaN   5800.00

Year                   1986      1987     1988      1989  ...      2010  \
Make       Model                                          ...
Ford       Fiesta       NaN       NaN      NaN       NaN  ...   2000.00
           Focus   88994.59 121900.00 95989.17 115500.00  ... 120183.76
           Mondeo       NaN       NaN      NaN   8600.00  ...       NaN
Skoda      Octavia   600.00  26700.00      NaN  91400.00  ...   3100.00
Toyota     Camry        NaN       NaN      NaN  22400.00  ...       NaN
           Corolla 16000.00   8000.00      NaN   4000.00  ...  24000.00
Volkswagen Golf         NaN   9300.00      NaN   8100.00  ...       NaN
           Jetta        NaN       NaN      NaN       NaN  ...       NaN
           Passat  15000.00  12300.00      NaN       NaN  ...   2800.00
           Touareg      NaN       NaN      NaN       NaN  ...   6300.00

Year                   2011      2012      2013      2014      2015     2016  \
Make       Model
Ford       Fiesta       NaN       NaN       NaN       NaN       NaN      NaN
           Focus   86689.17 115900.00 145494.59 158894.59 203694.59 72594.59
           Mondeo       NaN  34400.00       NaN       NaN       NaN 46200.00
Skoda      Octavia   500.00    500.00  13794.59   1900.00  46394.59   300.00
Toyota     Camry        NaN  16094.59       NaN       NaN       NaN 19000.00
           Corolla  8594.59       NaN       NaN       NaN       NaN      NaN
Volkswagen Golf      600.00       NaN   9300.00       NaN   2300.00      NaN
           Jetta        NaN       NaN       NaN       NaN       NaN      NaN
           Passat   3000.00   2000.00    300.00   8500.00   9194.59  2100.00
           Touareg      NaN       NaN       NaN   1300.00    500.00      NaN

Year                    2017      2018      2019
Make       Model
Ford       Fiesta        NaN       NaN       NaN
           Focus   272200.00 285194.59 101100.00
           Mondeo        NaN       NaN       NaN
Skoda      Octavia       NaN 171200.00   9500.00
Toyota     Camry     1000.00  13000.00  18100.00
           Corolla   9600.00       NaN  16000.00
Volkswagen Golf          NaN       NaN       NaN
           Jetta         NaN       NaN       NaN
           Passat        NaN       NaN       NaN
           Touareg       NaN       NaN       NaN

[10 rows x 40 columns]

## 6

In [48]:
owners.to_csv('owners.csv', sep=';', index=False)
fines.to_csv('fines.csv',  sep=';', index=False)

print('Part 4 is over!')

Part 4 is over!