In [57]:
import pandas as pd

## 1

In [58]:
views=pd.read_csv('../data/feed-views.log', delimiter='\t',  names=['date_time', 'user'])
views

                       date_time       user
0     2020-04-17 12:01:08.463179      artem
1     2020-04-17 12:01:23.743946      artem
2     2020-04-17 12:27:30.646665      artem
3     2020-04-17 12:35:44.884757      artem
4     2020-04-17 12:35:52.735016      artem
...                          ...        ...
1071  2020-05-21 18:45:20.441142  valentina
1072  2020-05-21 23:03:06.457819      maxim
1073  2020-05-21 23:23:49.995349      pavel
1074  2020-05-21 23:49:22.386789      artem
1075  2020-05-22 10:36:14.662600      artem

[1076 rows x 2 columns]

In [59]:
views = views.astype({'date_time':'datetime64[ns]', 'user':'object'})

In [60]:
print(views['date_time'].dtype)
print(views['user'].dtype)

datetime64[ns]
object

In [61]:
views['year']= views['date_time'].dt.year
views['month']= views['date_time'].dt.month 
views['day']= views['date_time'].dt.day
views['hour']=views['date_time'].dt.hour
views['minute']= views['date_time'].dt.minute 
views['second']=  views['date_time'].dt.second

In [62]:
views

,date_time,user,year,month,day,hour,minute,second
0,2020-04-17 12:01:08.463179,artem,2020,4,17,12,1,8
1,2020-04-17 12:01:23.743946,artem,2020,4,17,12,1,23
2,2020-04-17 12:27:30.646665,artem,2020,4,17,12,27,30
3,2020-04-17 12:35:44.884757,artem,2020,4,17,12,35,44
4,2020-04-17 12:35:52.735016,artem,2020,4,17,12,35,52
...,...,...,...,...,...,...,...,...
1071,2020-05-21 18:45:20.441142,valentina,2020,5,21,18,45,20
1072,2020-05-21 23:03:06.457819,maxim,2020,5,21,23,3,6
1073,2020-05-21 23:23:49.995349,pavel,2020,5,21,23,23,49
1074,2020-05-21 23:49:22.386789,artem,2020,5,21,23,49,22
1075,2020-05-22 10:36:14.662600,artem,2020,5,22,10,36,14

In [63]:
views.drop(columns=['date_time'], inplace=True)
views

           user  year  month  day  hour  minute  second
0         artem  2020      4   17    12       1       8
1         artem  2020      4   17    12       1      23
2         artem  2020      4   17    12      27      30
3         artem  2020      4   17    12      35      44
4         artem  2020      4   17    12      35      52
...         ...   ...    ...  ...   ...     ...     ...
1071  valentina  2020      5   21    18      45      20
1072      maxim  2020      5   21    23       3       6
1073      pavel  2020      5   21    23      23      49
1074      artem  2020      5   21    23      49      22
1075      artem  2020      5   22    10      36      14

[1076 rows x 7 columns]

## 2

In [ ]:
bins = [0, 4, 7, 11, 17, 20, 24]

day_times=['night', 'early morning', 'morning', 'afternoon', 'early evening', 'evening']

views['daytime'] = pd.cut(views['hour'], bins=bins, labels=day_times, right=False)

# Assigning day time couls be accomplished by .loc[] function
#EXAMPLE : 
# views.loc[(views['hour'] >= 0 ) & (views['hour'] < 4 ),'daytime'] = 'night'
# views.loc[(views['hour'] >= 4 ) & (views['hour'] < 7 ),'daytime'] = 'early morning'
# And we could continue in this fashion and only after 4 like this columns, that would be over!


views

           user  year  month  day  hour  minute  second        daytime
0         artem  2020      4   17    12       1       8      afternoon
1         artem  2020      4   17    12       1      23      afternoon
2         artem  2020      4   17    12      27      30      afternoon
3         artem  2020      4   17    12      35      44      afternoon
4         artem  2020      4   17    12      35      52      afternoon
...         ...   ...    ...  ...   ...     ...     ...            ...
1071  valentina  2020      5   21    18      45      20  early evening
1072      maxim  2020      5   21    23       3       6        evening
1073      pavel  2020      5   21    23      23      49        evening
1074      artem  2020      5   21    23      49      22        evening
1075      artem  2020      5   22    10      36      14        morning

[1076 rows x 8 columns]

In [65]:
views.set_index('user', inplace=True)

## 3

In [66]:
views.count()

year       1076
month      1076
day        1076
hour       1076
minute     1076
second     1076
daytime    1076
dtype: int64

In [67]:
views['daytime'].value_counts()

daytime
evening          509
afternoon        252
early evening    145
night            129
morning           36
early morning      5
Name: count, dtype: int64

## 4

In [69]:
views.sort_values(by=['hour', 'minute', 'second'], ascending=True, inplace=True)
views

           year  month  day  hour  minute  second  daytime
user
valentina  2020      5   15     0       0      13    night
valentina  2020      5   15     0       1       5    night
pavel      2020      5   12     0       1      27    night
pavel      2020      5   12     0       1      38    night
pavel      2020      5   12     0       1      55    night
...         ...    ...  ...   ...     ...     ...      ...
artem      2020      5   21    23      49      22  evening
anatoliy   2020      5    9    23      53      55  evening
pavel      2020      5    9    23      54      54  evening
valentina  2020      5   14    23      58      56  evening
alexander  2020      5   14    23      59      38  evening

[1076 rows x 7 columns]

## 5

In [70]:
views.loc[views['daytime'] == 'night', 'hour'].max()

3

In [71]:
views.loc[views['daytime'] == 'morning', 'hour'].min()

8

In [76]:
night_visiters=views.loc[views['hour']==3].index
print(night_visiters.tolist())

['konstantin', 'konstantin', 'konstantin']

In [77]:
morning_visitors=views.loc[views['hour']==8].index
print(morning_visitors.tolist())

['alexander', 'alexander']

In [78]:
views['hour'].mode()

0    22
Name: hour, dtype: int32

In [79]:
views['daytime'].mode()

0    evening
Name: daytime, dtype: category
Categories (6, object): ['night' < 'early morning' < 'morning' < 'afternoon' < 'early evening' < 'evening']

## 6

In [81]:
views['hour'].nsmallest(3)

user
valentina    0
valentina    0
pavel        0
Name: hour, dtype: int32

In [82]:
views['hour'].nlargest(3)

user
ekaterina    23
ekaterina    23
ekaterina    23
Name: hour, dtype: int32

## 7

In [84]:
views.describe(include='all')

,year,month,day,hour,minute,second,daytime
count,1076.0,1076.000000,1076.000000,1076.000000,1076.000000,1076.000000,1076
unique,NaN,NaN,NaN,NaN,NaN,NaN,6
top,NaN,NaN,NaN,NaN,NaN,NaN,evening
freq,NaN,NaN,NaN,NaN,NaN,NaN,509
mean,2020.0,4.870818,13.552974,16.249071,29.629182,29.500929,NaN
std,0.0,0.335557,4.906567,6.955490,17.689388,17.405506,NaN
min,2020.0,4.000000,1.000000,0.000000,0.000000,0.000000,NaN
25%,2020.0,5.000000,11.000000,13.000000,14.000000,14.000000,NaN
50%,2020.0,5.000000,13.000000,19.000000,29.000000,30.000000,NaN
75%,2020.0,5.000000,15.000000,22.000000,46.000000,45.000000,NaN
max,2020.0,5.000000,30.000000,23.000000,59.000000,59.000000,NaN

In [90]:
hour_Q1=13.0
hour_Q3=22.0
iqr=hour_Q3-hour_Q1
print('50% Users Visit in this interval : ',iqr)

50% Users Visit in this interval :  9.0