In [22]:
import pandas as pd

## 1

In [23]:
auto_df=pd.read_csv("../data/auto.csv", index_col='ID')
auto_df

        CarNumber    Make_n_model  Refund    Fines  History
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.0      NaN
1     E432XX77RUS    Toyota Camry     1.0   6500.0      NaN
2     7184TT36RUS      Ford Focus     1.0   2100.0      NaN
3    X582HE161RUS      Ford Focus     2.0   2000.0      NaN
4    E34877152RUS      Ford Focus     2.0   6100.0      NaN
..            ...             ...     ...      ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.0      NaN
927  M0309X197RUS      Ford Focus     1.0  22300.0      NaN
928  O673E8197RUS      Ford Focus     2.0    600.0      NaN
929  8610T8154RUS      Ford Focus     1.0   2000.0      NaN
930  H419XE197RUS  Toyota Corolla     2.0      NaN      2.0

[931 rows x 5 columns]

## 2

In [24]:
auto_df.count()

CarNumber       931
Make_n_model    931
Refund          914
Fines           869
History          82
dtype: int64

## 3

In [25]:
auto_df.drop_duplicates(subset=['CarNumber', 'Make_n_model', 'Fines'], keep='last', inplace=True)
auto_df.count()

CarNumber       725
Make_n_model    725
Refund          713
Fines           665
History          65
dtype: int64

## 4

In [26]:
auto_df.isna().sum()

CarNumber         0
Make_n_model      0
Refund           12
Fines            60
History         660
dtype: int64

### History column is more than 500 missing values, so I must to drop duplicates!

In [27]:
auto_df.drop(columns='History', inplace=True)
auto_df

        CarNumber    Make_n_model  Refund    Fines
ID
0    Y163O8161RUS      Ford Focus     2.0   3200.0
1     E432XX77RUS    Toyota Camry     1.0   6500.0
2     7184TT36RUS      Ford Focus     1.0   2100.0
3    X582HE161RUS      Ford Focus     2.0   2000.0
5    92918M178RUS      Ford Focus     1.0   5700.0
..            ...             ...     ...      ...
926  Y163O8161RUS      Ford Focus     2.0   1600.0
927  M0309X197RUS      Ford Focus     1.0  22300.0
928  O673E8197RUS      Ford Focus     2.0    600.0
929  8610T8154RUS      Ford Focus     1.0   2000.0
930  H419XE197RUS  Toyota Corolla     2.0      NaN

[725 rows x 4 columns]

In [28]:
auto_df['Refund'] = auto_df['Refund'].ffill()
auto_df.isna().sum()

CarNumber        0
Make_n_model     0
Refund           0
Fines           60
dtype: int64

In [29]:
auto_df['Fines'].fillna(auto_df['Fines'].mean(),inplace=True)
auto_df.isna().sum()

/tmp/ipykernel_7052/1257872788.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  auto_df['Fines'].fillna(auto_df['Fines'].mean(),inplace=True)

CarNumber       0
Make_n_model    0
Refund          0
Fines           0
dtype: int64

## 5

In [30]:
auto_df[['Make', 'Model']] = auto_df['Make_n_model'].str.split(' ', expand=True)
auto_df.drop(columns='Make_n_model', inplace=True)
auto_df

        CarNumber  Refund         Fines    Make    Model
ID
0    Y163O8161RUS     2.0   3200.000000    Ford    Focus
1     E432XX77RUS     1.0   6500.000000  Toyota    Camry
2     7184TT36RUS     1.0   2100.000000    Ford    Focus
3    X582HE161RUS     2.0   2000.000000    Ford    Focus
5    92918M178RUS     1.0   5700.000000    Ford    Focus
..            ...     ...           ...     ...      ...
926  Y163O8161RUS     2.0   1600.000000    Ford    Focus
927  M0309X197RUS     1.0  22300.000000    Ford    Focus
928  O673E8197RUS     2.0    600.000000    Ford    Focus
929  8610T8154RUS     1.0   2000.000000    Ford    Focus
930  H419XE197RUS     2.0   8594.586466  Toyota  Corolla

[725 rows x 5 columns]

In [31]:
auto_df.to_json('auto.json',orient='records', indent=4)
auto_df.count()

CarNumber    725
Refund       725
Fines        725
Make         725
Model        716
dtype: int64