In [1]:
import pandas as pd

## 1

In [2]:
auto_df = pd.read_json('../ex02/auto.json')
auto_df.set_index('CarNumber', inplace=True)
auto_df

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
E432XX77RUS        1   6500.000000  Toyota    Camry
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[725 rows x 4 columns]

## 2

In [3]:
auto_df.loc[auto_df['Fines'] >= 2100]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
E432XX77RUS        1   6500.000000      Toyota    Camry
7184TT36RUS        1   2100.000000        Ford    Focus
92918M178RUS       1   5700.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
...              ...           ...         ...      ...
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
O22097197RUS       1  24300.000000        Ford    Focus
M0309X197RUS       1  22300.000000        Ford    Focus
H419XE197RUS       2   8594.586466      Toyota  Corolla

[459 rows x 4 columns]

In [4]:
auto_df.loc[(auto_df['Fines'] >= 2100) & (auto_df['Refund'] == 2)]

              Refund         Fines        Make    Model
CarNumber
Y163O8161RUS       2   3200.000000        Ford    Focus
H234YH197RUS       2   6000.000000        Ford    Focus
707987163RUS       2   2200.000000        Ford    Focus
K330T8197RUS       2   8200.000000       Skoda  Octavia
M592CH197RUS       2   8594.586466       Skoda  Octavia
...              ...           ...         ...      ...
O136HO197RUS       2   7800.000000      Toyota  Corolla
O68897197RUS       2  12300.000000        Ford    Focus
O718MM163RUS       2   8594.586466        Ford    Focus
7065C8197RUS       2  11400.000000  Volkswagen   Passat
H419XE197RUS       2   8594.586466      Toyota  Corolla

[312 rows x 4 columns]

In [5]:
auto_df.loc[(auto_df['Model'] == 'Focus') | (auto_df['Model'] == 'Corolla')]

              Refund         Fines    Make    Model
CarNumber
Y163O8161RUS       2   3200.000000    Ford    Focus
7184TT36RUS        1   2100.000000    Ford    Focus
X582HE161RUS       2   2000.000000    Ford    Focus
92918M178RUS       1   5700.000000    Ford    Focus
H234YH197RUS       2   6000.000000    Ford    Focus
...              ...           ...     ...      ...
Y163O8161RUS       2   1600.000000    Ford    Focus
M0309X197RUS       1  22300.000000    Ford    Focus
O673E8197RUS       2    600.000000    Ford    Focus
8610T8154RUS       1   2000.000000    Ford    Focus
H419XE197RUS       2   8594.586466  Toyota  Corolla

[593 rows x 4 columns]

In [6]:
car_numbers = ['Y7689C197RUS', '92928M178RUS', '7788KT197RUS', 'H115YO163RUS', 'X758HY197RUS']
auto_df.loc[auto_df.index.isin(car_numbers)]

# OR I CAN USE .apply() FUNCTION TO CHECK THIS CASE!
# auto_df.loc[auto_df['CarNumber']].apply(lambda x: x in car_numbers)

              Refund          Fines  Make  Model
CarNumber
92928M178RUS       1    8594.586466  Ford  Focus
H115YO163RUS       1    2200.000000  Ford  Focus
7788KT197RUS       2   12000.000000  Ford  Focus
X758HY197RUS       2   24200.000000  Ford  Focus
X758HY197RUS       2   72600.000000  Ford  Focus
Y7689C197RUS       1   27000.000000  Ford  Focus
92928M178RUS       1     600.000000  Ford  Focus
H115YO163RUS       1    8594.586466  Ford  Focus
H115YO163RUS       2    1100.000000  Ford  Focus
7788KT197RUS       2    8594.586466  Ford  Focus
7788KT197RUS       1   20000.000000  Ford  Focus
X758HY197RUS       2  145200.000000  Ford  Focus
92928M178RUS       1    1200.000000  Ford  Focus
Y7689C197RUS       2    9000.000000  Ford  Focus
Y7689C197RUS       2   45000.000000  Ford  Focus
7788KT197RUS       2    4000.000000  Ford  Focus
Y7689C197RUS       1   36000.000000  Ford  Focus
92928M178RUS       2    3000.000000  Ford  Focus

## 3

In [7]:
auto_df.groupby('Make')['Fines'].median()

Make
Audi          4200.0
BMW           6500.0
Ford          3500.0
Skoda         3250.0
Toyota        7700.0
Volkswagen    4300.0
Volvo         8500.0
Name: Fines, dtype: float64

In [8]:
auto_df.groupby(['Make', 'Model'])['Fines'].median()

Make        Model
Ford        Focus      3500.0
            Mondeo     7650.0
Skoda       Octavia    3250.0
Toyota      Camry      7700.0
            Corolla    7700.0
Volkswagen  Golf       4800.0
            Jetta      2800.0
            Passat     3500.0
            Touareg    5800.0
Name: Fines, dtype: float64

In [9]:
auto_df.groupby(['Make', 'Model'])['Fines'].value_counts()

Make        Model    Fines
Ford        Focus    8594.586466    45
                     500.000000     44
                     1000.000000    34
                     2000.000000    24
                     1500.000000    20
                                    ..
Volkswagen  Touareg  500.000000      1
                     1300.000000     1
                     5800.000000     1
                     6300.000000     1
                     8594.586466     1
Name: count, Length: 288, dtype: int64

In [10]:
print('Minimum Values :')
print(auto_df.groupby(['Make', 'Model'])['Fines'].min())
print('Maximum Values :')
print(auto_df.groupby(['Make', 'Model'])['Fines'].max())

Minimum Values :
Make        Model
Ford        Focus       100.0
            Mondeo     1100.0
Skoda       Octavia     300.0
Toyota      Camry       500.0
            Corolla     900.0
Volkswagen  Golf        200.0
            Jetta       500.0
            Passat      100.0
            Touareg     500.0
Name: Fines, dtype: float64
Maximum Values :
Make        Model
Ford        Focus      180000.000000
            Mondeo      46200.000000
Skoda       Octavia    145000.000000
Toyota      Camry       22400.000000
            Corolla     34300.000000
Volkswagen  Golf       168000.000000
            Jetta       46000.000000
            Passat      29700.000000
            Touareg      8594.586466
Name: Fines, dtype: float64

In [11]:
print('Standard Deviation :')
print(auto_df.groupby(['Make', 'Model'])['Fines'].std())

Standard Deviation :
Make        Model
Ford        Focus      15041.269437
            Mondeo     18987.329108
Skoda       Octavia    24339.742174
Toyota      Camry       6410.250654
            Corolla     9629.325617
Volkswagen  Golf       36950.839950
            Jetta      17743.026799
            Passat      6969.739135
            Touareg     3461.778173
Name: Fines, dtype: float64

## 4

In [12]:
auto_df.groupby(auto_df.index)['Fines'].count().sort_values(ascending=False)

CarNumber
Y7689C197RUS    4
7788KT197RUS    4
92928M178RUS    4
Y7129Y50RUS     3
X758HY197RUS    3
               ..
Y967O8197RUS    1
Y965O8197RUS    1
Y965EE197RUS    1
Y964O8197RUS    1
Y964EE197RUS    1
Name: Fines, Length: 531, dtype: int64

In [13]:
top_car = auto_df.index.value_counts().index[0]

top_car_df = auto_df[auto_df.index == top_car]
top_car_df

              Refund        Fines  Make  Model
CarNumber
92928M178RUS       1  8594.586466  Ford  Focus
92928M178RUS       1   600.000000  Ford  Focus
92928M178RUS       1  1200.000000  Ford  Focus
92928M178RUS       2  3000.000000  Ford  Focus

In [14]:
auto_df.groupby(auto_df.index)['Fines'].sum().sort_values(ascending=False)

CarNumber
X758HY197RUS    242000.0
9020YC197RUS    217500.0
M0279X197RUS    216000.0
Y352O8197RUS    207200.0
Y778EE197RUS    192000.0
                  ...
Y166O8161RUS       100.0
K326T8197RUS       100.0
Y195O8161RUS       100.0
C58078163RUS       100.0
705787163RUS       100.0
Name: Fines, Length: 531, dtype: float64

In [15]:
top_payer=auto_df.groupby(auto_df.index)['Fines'].sum().idxmax()
auto_df.loc[auto_df.index == top_payer]

              Refund     Fines  Make  Model
CarNumber
X758HY197RUS       2   24200.0  Ford  Focus
X758HY197RUS       2   72600.0  Ford  Focus
X758HY197RUS       2  145200.0  Ford  Focus

In [16]:
check_number=auto_df.groupby(auto_df.index)['Model'].nunique()

if len(check_number[check_number > 1 ]) > 0:
    print("Yes, there are car numbers belongs to different models:")
    print(check_number[check_number > 1 ])
else:
    print('No, there is no rule-breakers!')

No, there is no rule-breakers!

In [24]:
check_number[1]

/tmp/ipykernel_13507/1461899593.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  check_number[1]

np.int64(1)